// AUTO-GENERATED FILE.
// This file is auto-generated by the Ballerina OpenAPI tool.

import ballerina/http;

listener http:Listener ep0 = new (9090);

service http:InterceptableService / on ep0 {

    public function createInterceptors() returns AssertionInterceptor => new;

    # Delete a to-do item
    #
    # + return - returns can be any of following types
    # http:NoContent (Deleted)
    # http:Unauthorized (Not signed in)
    # http:NotFound (Not found (not the caller's item, or does not exist))
    resource function delete me/todos/[string todoId](http:RequestContext ctx) returns http:NoContent|ErrorUnauthorized|ErrorNotFound|error {
        GatewayCaller? caller = gatewayCaller(ctx);
        if caller is () {
            return unauthorizedError();
        }
        boolean deleted = check deleteTodo(caller.userId, todoId);
        if !deleted {
            return notFoundError();
        }
        return http:NO_CONTENT;
    }

    # The caller's to-do items
    #
    # + completed - filter by completion status
    # + return - returns can be any of following types
    # http:Ok (Page of the caller's to-do items)
    # http:Unauthorized (Not signed in)
    resource function get me/todos(http:RequestContext ctx, boolean? completed, int 'limit = 20, int offset = 0) returns inline_response_200|ErrorUnauthorized|error {
        GatewayCaller? caller = gatewayCaller(ctx);
        if caller is () {
            return unauthorizedError();
        }
        int pageLimit = 'limit > 100 ? 100 : 'limit;
        pageLimit = pageLimit < 0 ? 0 : pageLimit;
        int pageOffset = offset < 0 ? 0 : offset;

        TodoPage page = check listTodos(caller.userId, pageLimit, pageOffset, completed);
        string? next = pageOffset + pageLimit < page.count ? buildPageLink(pageLimit, pageOffset + pageLimit, completed) : ();
        int previousOffset = pageOffset - pageLimit < 0 ? 0 : pageOffset - pageLimit;
        string? previous = pageOffset > 0 ? buildPageLink(pageLimit, previousOffset, completed) : ();

        inline_response_200 response = {
            count: page.count,
            data: page.data,
            next: next,
            previous: previous
        };
        return response;
    }

    # A single to-do item of the caller's
    #
    # + return - returns can be any of following types
    # http:Ok (The to-do item)
    # http:Unauthorized (Not signed in)
    # http:NotFound (Not found (not the caller's item, or does not exist))
    resource function get me/todos/[string todoId](http:RequestContext ctx) returns TodoItem|ErrorUnauthorized|ErrorNotFound|error {
        GatewayCaller? caller = gatewayCaller(ctx);
        if caller is () {
            return unauthorizedError();
        }
        TodoItem? item = check getTodo(caller.userId, todoId);
        if item is () {
            return notFoundError();
        }
        return item;
    }

    # Update title, description, or completion status
    #
    # + return - returns can be any of following types
    # http:Ok (Updated to-do item)
    # http:BadRequest (Invalid input)
    # http:Unauthorized (Not signed in)
    # http:NotFound (Not found (not the caller's item, or does not exist))
    resource function patch me/todos/[string todoId](http:RequestContext ctx, @http:Payload TodoItemUpdate payload) returns TodoItem|ErrorBadRequest|ErrorUnauthorized|ErrorNotFound|error {
        GatewayCaller? caller = gatewayCaller(ctx);
        if caller is () {
            return unauthorizedError();
        }
        string? updateTitle = payload?.title;
        if updateTitle is string && updateTitle.trim().length() == 0 {
            return badRequestError("title must not be blank");
        }
        TodoItem? updated = check updateTodo(caller.userId, todoId, payload);
        if updated is () {
            return notFoundError();
        }
        return updated;
    }

    # Create a to-do item for the caller
    #
    # + return - returns can be any of following types
    # http:Created (Created to-do item)
    # http:BadRequest (Invalid input)
    # http:Unauthorized (Not signed in)
    resource function post me/todos(http:RequestContext ctx, @http:Payload TodoItemInput payload) returns TodoItem|ErrorBadRequest|ErrorUnauthorized|error {
        GatewayCaller? caller = gatewayCaller(ctx);
        if caller is () {
            return unauthorizedError();
        }
        string title = payload.title.trim();
        if title.length() == 0 {
            return badRequestError("title is required");
        }
        payload.title = title;
        TodoItem created = check createTodo(caller.userId, payload);
        return created;
    }
}

public type ErrorNotFound record {|
    *http:NotFound;
    Error body;
|};

public type TodoItem record {
    # to-do item id
    string id;
    # short task title
    string title;
    # optional longer detail
    string description?;
    # whether the item is done
    boolean completed;
    string createdAt;
    string updatedAt;
};

public type TodoItemUpdate record {
    string title?;
    string description?;
    boolean completed?;
};

public type inline_response_200 record {
    # total matching items
    int count;
    # relative URI of the next page
    string? next?;
    # relative URI of the previous page
    string? previous?;
    TodoItem[] data;
};

public type Error record {
    # HTTP or application error code
    int code;
    # short human-readable label
    string message;
    # detailed explanation
    string description?;
    # URI to documentation
    string moreInfo?;
};

public type ErrorBadRequest record {|
    *http:BadRequest;
    Error body;
|};

public type TodoItemInput record {
    string title;
    string description?;
};

public type ErrorUnauthorized record {|
    *http:Unauthorized;
    Error body;
|};
